version: '3.6'
services:
  api:
    build:
      context: ./inventory-api
    container_name: inventory-api
    ports:
      - "8080"
  client:
    build:
      context: ./web-client
    container_name: web-client
    restart: always
    depends_on:
      - api
    links:
      - "api:inventory-api"
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
